apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: aicore-train-pipeline # executable id, must be unique across all your workflows (YAML files), please modify this to any value (e.g. code-pipeline-12345) if you are not the only user of your SAP AI Core instance.
  annotations:
    scenarios.ai.sap.com/description: "SAP AI Core training"
    scenarios.ai.sap.com/name: "House Price Predictor Training Demo"
    executables.ai.sap.com/description: "Train DTRegressor with live data"
    executables.ai.sap.com/name: "training"
  labels:
    scenarios.ai.sap.com/id: "train-demo"
    ai.sap.com/version: "1.8"
spec:
  imagePullSecrets:
    - name: secret # your docker registry secret
  entrypoint: training-pipeline
  arguments:
    parameters: # placeholder for string like inputs
        - name: DT_MAX_DEPTH # identifier local to this workflow
        - name: MAX_FEATURES
        - name: MIN_SAMPLES_SPLIT
  templates:
  - name: training-pipeline
    steps:
    - - name: trainer
        template: trainer

  - name: trainer
    metadata:
      labels:
        ai.sap.com/resourcePlan: train.l
    inputs:
      artifacts:
        - name: house_dataset
          path: /app/data/
      
    outputs:
      artifacts: 
        - name: house_model
          globalName: housemodel # name of the artifact generated, and folder name when placed in S3, complete directory will be `../<executaion_id>/housemodel`. Also used above in annotation
          path: /app/model/ # from which folder in docker image (after running workflow step) copy contents to cloud storage
          archive:
            none:   # specify not to compress while uploading to cloud
              {}

    container:
      image: docker.io/amanichopra/aicore-train:latest # Your docker image name
      command: ["/bin/sh", "-c"]
      env:
        - name: DT_MAX_DEPTH
          value: "{{workflow.parameters.DT_MAX_DEPTH}}"
        - name: MAX_FEATURES
          value: "{{workflow.parameters.MAX_FEATURES}}"
        - name: MIN_SAMPLES_SPLIT
          value: "{{workflow.parameters.MIN_SAMPLES_SPLIT}}"
      args:
        - "python /app/src/train_movenet.py"